export const seedProductsIfood = [
  {
    "code": "285",
    "name": "Copo Térmico",
    "category": "Acessório",
    "size": "Único",
    "cost": "26.10",
    "margin": "122.22",
    "price": "58.00",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "287",
    "name": "Calcinha S/Costura",
    "category": "Acessório",
    "size": "Único",
    "cost": "7.16",
    "margin": "122.07",
    "price": "15.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "288",
    "name": "Meia Basic - Allure",
    "category": "Acessório",
    "size": "Único",
    "cost": "8.05",
    "margin": "122.36",
    "price": "17.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "289",
    "name": "Luva Silicone",
    "category": "Acessório",
    "size": "Único",
    "cost": "13.46",
    "margin": "122.14",
    "price": "29.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "290",
    "name": "Strap",
    "category": "Acessório",
    "size": "Único",
    "cost": "13.05",
    "margin": "122.22",
    "price": "29.00",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "291",
    "name": "Mini Band - Elástico",
    "category": "Acessório",
    "size": "Único",
    "cost": "8.96",
    "margin": "122.10",
    "price": "19.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "292",
    "name": "Mini Band - Tecido",
    "category": "Acessório",
    "size": "Único",
    "cost": "13.46",
    "margin": "122.14",
    "price": "29.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "293",
    "name": "Faixa de Cabelo",
    "category": "Acessório",
    "size": "Único",
    "cost": "3.56",
    "margin": "121.91",
    "price": "7.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "294",
    "name": "Copo Mixer",
    "category": "Acessório",
    "size": "Único",
    "cost": "17.50",
    "margin": "122.29",
    "price": "38.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "295",
    "name": "Mala",
    "category": "Acessório",
    "size": "Único",
    "cost": "23.80",
    "margin": "122.27",
    "price": "52.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "183",
    "name": "Calça Legging - Alpha",
    "category": "Calça",
    "size": "Único",
    "cost": "58.46",
    "margin": "122.20",
    "price": "129.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "244",
    "name": "Calça Basic Duo",
    "category": "Calça",
    "size": "Único",
    "cost": "73.31",
    "margin": "122.21",
    "price": "162.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "298",
    "name": "Calça Flare",
    "category": "Calça",
    "size": "Único",
    "cost": "77.81",
    "margin": "122.21",
    "price": "172.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "299",
    "name": "Calça com bolso",
    "category": "Calça",
    "size": "Único",
    "cost": "53.96",
    "margin": "122.20",
    "price": "119.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "156",
    "name": "Bermuda Dry Fit - Alpha",
    "category": "Camisa",
    "size": "Único",
    "cost": "31.46",
    "margin": "122.19",
    "price": "69.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "166",
    "name": "Camiseta Apex - Alpha",
    "category": "Camisa",
    "size": "Único",
    "cost": "45.00",
    "margin": "122.20",
    "price": "99.99",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "170",
    "name": "Camiseta Oversized - Alpha",
    "category": "Camisa",
    "size": "Único",
    "cost": "44.96",
    "margin": "122.20",
    "price": "99.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "172",
    "name": "Camiseta Poliamida - Alpha",
    "category": "Camisa",
    "size": "Único",
    "cost": "35.96",
    "margin": "122.19",
    "price": "79.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "176",
    "name": "Camiseta Dry Fit Masc - Alpha",
    "category": "Camisa",
    "size": "Único",
    "cost": "26.95",
    "margin": "122.26",
    "price": "59.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "177",
    "name": "Camiseta Tule - Fem.",
    "category": "Camisa",
    "size": "Único",
    "cost": "37.76",
    "margin": "122.19",
    "price": "83.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "178",
    "name": "Camiseta Dry Fit Fem - Alpha",
    "category": "Camisa",
    "size": "Único",
    "cost": "26.95",
    "margin": "122.26",
    "price": "59.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "179",
    "name": "Camiseta T-shirt Fem",
    "category": "Camisa",
    "size": "Único",
    "cost": "17.95",
    "margin": "122.28",
    "price": "39.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "194",
    "name": "Blusas Variadas",
    "category": "Camisa",
    "size": "Único",
    "cost": "32.81",
    "margin": "122.19",
    "price": "72.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "243",
    "name": "Camiseta Básica - Alpha",
    "category": "Camisa",
    "size": "Único",
    "cost": "35.96",
    "margin": "122.19",
    "price": "79.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "204",
    "name": "Conj. Calça - Liso Allure",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "83.66",
    "margin": "122.21",
    "price": "185.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "207",
    "name": "Conj. Calça Onça - Top Faixa",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "98.95",
    "margin": "122.23",
    "price": "219.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "212",
    "name": "Conj. Calça Duo + Top Faixa",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "129.56",
    "margin": "122.21",
    "price": "287.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "222",
    "name": "Conj. Calça Val Costura - Allure",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "89.51",
    "margin": "122.21",
    "price": "198.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "223",
    "name": "Conj. Calça Basic - Allure",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "80.51",
    "margin": "122.21",
    "price": "178.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "224",
    "name": "Conj. Flare Top Faixa",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "89.51",
    "margin": "122.21",
    "price": "198.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "228",
    "name": "Conj. Calça G Compressão - Allure",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "112.01",
    "margin": "122.21",
    "price": "248.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "231",
    "name": "Conj. Calça Compressão - Allure",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "107.95",
    "margin": "122.23",
    "price": "239.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "234",
    "name": "Conj. Calça Onça",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "89.95",
    "margin": "122.23",
    "price": "199.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "236",
    "name": "Conj. Calça Comfy",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "94.45",
    "margin": "122.23",
    "price": "209.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "248",
    "name": "Conj. Calça - Top Cropped Cruzado Ad.",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "85.45",
    "margin": "122.24",
    "price": "189.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "249",
    "name": "Conj. Calça Flare Ad.",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "107.51",
    "margin": "122.21",
    "price": "238.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "250",
    "name": "Conj. Calça Trio Ad.",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "103.28",
    "margin": "122.21",
    "price": "229.50",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "251",
    "name": "Conj. Calça Menta Ad.",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "84.56",
    "margin": "122.21",
    "price": "187.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "252",
    "name": "Conj. Calça Trio Manga Longa Ad.",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "97.16",
    "margin": "122.21",
    "price": "215.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "253",
    "name": "Conj. Calça - Top Tiras Ad.",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "97.16",
    "margin": "122.21",
    "price": "215.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "258",
    "name": "Conj. Calça + Top Faixa Lumini",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "84.56",
    "margin": "122.21",
    "price": "187.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "259",
    "name": "Conj. Calça Glow - Leve Comp.",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "84.38",
    "margin": "122.21",
    "price": "187.50",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "260",
    "name": "Conj. Calça Glow PL - Leve Comp",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "113.36",
    "margin": "122.21",
    "price": "251.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "270",
    "name": "Conj. Calça Pantalona",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "89.95",
    "margin": "122.23",
    "price": "199.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "272",
    "name": "Conj. Calça + Top Cropped",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "84.11",
    "margin": "122.21",
    "price": "186.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "273",
    "name": "Conj. Calça + Top Pto/bco",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "78.21",
    "margin": "122.22",
    "price": "173.80",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "274",
    "name": "Conj. Calça C/Bolso Liso",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "74.20",
    "margin": "122.24",
    "price": "164.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "275",
    "name": "Conj. Calça C/Bolso Basic",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "89.51",
    "margin": "122.21",
    "price": "198.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "276",
    "name": "Conj. Calça Flare Frente Única",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "113.81",
    "margin": "122.21",
    "price": "252.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "277",
    "name": "Conj. Calça Flare + Top Enrug.",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "104.81",
    "margin": "122.21",
    "price": "232.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "278",
    "name": "Conj, Calça Basic FB",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "85.45",
    "margin": "122.24",
    "price": "189.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "279",
    "name": "Conj. Calça + Top Faixa Liso",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "85.45",
    "margin": "122.24",
    "price": "189.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "280",
    "name": "Conj. Calça S/Bolso - Top Cropped",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "87.70",
    "margin": "122.23",
    "price": "194.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "282",
    "name": "Conj. Calça C/Bolso + Top Nadador",
    "category": "Conjunto Calça",
    "size": "Único",
    "cost": "89.51",
    "margin": "122.21",
    "price": "198.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "200",
    "name": "Conj. Short Jaquard Comfy",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "83.16",
    "margin": "122.22",
    "price": "184.80",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "211",
    "name": "Conj. Short Glow - Allure",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "78.70",
    "margin": "122.24",
    "price": "174.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "232",
    "name": "Conj. Short Compressão C/Bolso",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "85.45",
    "margin": "122.24",
    "price": "189.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "233",
    "name": "Conj. Short S/Bolso",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "85.45",
    "margin": "122.24",
    "price": "189.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "235",
    "name": "Conj. Short Onça",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "80.95",
    "margin": "122.24",
    "price": "179.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "245",
    "name": "Conj. Short Duo - Top Faixa - Allure",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "87.08",
    "margin": "122.21",
    "price": "193.50",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "254",
    "name": "Conj. Short Trio Lulu Ad.",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "101.20",
    "margin": "122.23",
    "price": "224.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "255",
    "name": "Conj. Short Trio Hy Ad.",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "95.76",
    "margin": "122.22",
    "price": "212.80",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "256",
    "name": "Conj. Short Beach Lisa",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "84.38",
    "margin": "122.21",
    "price": "187.50",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "263",
    "name": "Conj. Short C/Bolso PL",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "107.06",
    "margin": "122.21",
    "price": "237.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "264",
    "name": "Conj. Short Beach - Cropped Manga Longa",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "77.49",
    "margin": "122.22",
    "price": "172.20",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "266",
    "name": "Conj. Short Trio Glow",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "111.38",
    "margin": "122.21",
    "price": "247.50",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "269",
    "name": "Conj. Short Saia Trio",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "93.56",
    "margin": "122.21",
    "price": "207.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "271",
    "name": "Conj. Short Basic",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "67.45",
    "margin": "122.24",
    "price": "149.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "281",
    "name": "Conj. Short Canelado",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "68.81",
    "margin": "122.21",
    "price": "152.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "283",
    "name": "Conj. Short Duo Empina",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "86.81",
    "margin": "122.21",
    "price": "192.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "284",
    "name": "Conj. Short BMQ",
    "category": "Conjunto Short",
    "size": "Único",
    "cost": "62.96",
    "margin": "122.20",
    "price": "139.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "157",
    "name": "Jaqueta Corta Vento - Fem.",
    "category": "Jaqueta",
    "size": "Único",
    "cost": "58.46",
    "margin": "122.20",
    "price": "129.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "169",
    "name": "Jaqueta Lululemon - Authênticas Fem.",
    "category": "Jaqueta",
    "size": "Único",
    "cost": "83.66",
    "margin": "122.21",
    "price": "185.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "175",
    "name": "Jaqueta Lululemon - Fem.",
    "category": "Jaqueta",
    "size": "Único",
    "cost": "58.46",
    "margin": "122.20",
    "price": "129.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "202",
    "name": "Macacão Mel Liso",
    "category": "Macacão",
    "size": "Único",
    "cost": "105.70",
    "margin": "122.23",
    "price": "234.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "208",
    "name": "Macacão Ju - Onça",
    "category": "Macacão",
    "size": "Único",
    "cost": "112.45",
    "margin": "122.23",
    "price": "249.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "209",
    "name": "Macacão M. Manca - Onça",
    "category": "Macacão",
    "size": "Único",
    "cost": "112.45",
    "margin": "122.23",
    "price": "249.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "210",
    "name": "Macacão Costura - Onça",
    "category": "Macacão",
    "size": "Único",
    "cost": "112.45",
    "margin": "122.23",
    "price": "249.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "217",
    "name": "Macacão Flare Trança - Allure",
    "category": "Macacão",
    "size": "Único",
    "cost": "126.72",
    "margin": "122.22",
    "price": "281.60",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "218",
    "name": "Macacão Larg Alças - Allure",
    "category": "Macacão",
    "size": "Único",
    "cost": "120.55",
    "margin": "122.23",
    "price": "267.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "220",
    "name": "Macacão Costura Text. - Allure",
    "category": "Macacão",
    "size": "Único",
    "cost": "109.76",
    "margin": "122.21",
    "price": "243.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "221",
    "name": "Macaquinho T.C Liso - Allure",
    "category": "Macacão",
    "size": "Único",
    "cost": "94.45",
    "margin": "122.23",
    "price": "209.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "226",
    "name": "Macacão Compressão",
    "category": "Macacão",
    "size": "Único",
    "cost": "116.95",
    "margin": "122.23",
    "price": "259.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "239",
    "name": "Macacão Compressão Duo Glow",
    "category": "Macacão",
    "size": "Único",
    "cost": "114.70",
    "margin": "122.23",
    "price": "254.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "261",
    "name": "Macacão Glow PL",
    "category": "Macacão",
    "size": "Único",
    "cost": "130.00",
    "margin": "122.23",
    "price": "288.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "265",
    "name": "Macacão Jaquard - Allure",
    "category": "Macacão",
    "size": "Único",
    "cost": "80.33",
    "margin": "122.21",
    "price": "178.50",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "296",
    "name": "macacão Paty",
    "category": "Macacão",
    "size": "Único",
    "cost": "98.06",
    "margin": "122.21",
    "price": "217.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "201",
    "name": "Macaquinho Mel Liso",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "94.45",
    "margin": "122.23",
    "price": "209.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "203",
    "name": "Macaquinho T.C Duo Liso",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "88.16",
    "margin": "122.21",
    "price": "195.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "205",
    "name": "Macaquinho T.C - Onça",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "98.28",
    "margin": "122.22",
    "price": "218.40",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "206",
    "name": "Macaquinho Mel - Onça",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "98.28",
    "margin": "122.22",
    "price": "218.40",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "213",
    "name": "Macaquinho Bolso Duo",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "94.45",
    "margin": "122.23",
    "price": "209.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "214",
    "name": "Macaquinho Lais - Allure",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "94.45",
    "margin": "122.23",
    "price": "209.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "215",
    "name": "Macaquinho Frente Única - Allure",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "98.06",
    "margin": "122.21",
    "price": "217.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "216",
    "name": "Macaquinho Manga Longa - Allure",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "101.61",
    "margin": "122.22",
    "price": "225.80",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "219",
    "name": "Macaquinho M.Manca - Allure",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "96.39",
    "margin": "122.22",
    "price": "214.20",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "225",
    "name": "Macaquinho Textura Manga - Allure",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "103.01",
    "margin": "122.21",
    "price": "228.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "227",
    "name": "Macaquinho Compressão Basic - Allure",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "103.01",
    "margin": "122.21",
    "price": "228.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "229",
    "name": "Macaquinho Alcinha Textura",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "98.95",
    "margin": "122.23",
    "price": "219.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "230",
    "name": "Macaquinho Manguinha Onça",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "98.95",
    "margin": "122.23",
    "price": "219.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "237",
    "name": "Macaquinho Basic - Allure",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "94.45",
    "margin": "122.23",
    "price": "209.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "238",
    "name": "Macaquinho Bicolor M.Manca - Allure",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "103.01",
    "margin": "122.21",
    "price": "228.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "240",
    "name": "Macaquinho Manguinha Liso - Allure",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "94.45",
    "margin": "122.23",
    "price": "209.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "241",
    "name": "Macaquinho Jaquard M. Manca",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "67.45",
    "margin": "122.24",
    "price": "149.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "242",
    "name": "Macaquinho Lisa M.Manca Glow",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "70.61",
    "margin": "122.21",
    "price": "156.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "246",
    "name": "Macaquinho Isa Ad.",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "85.45",
    "margin": "122.24",
    "price": "189.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "247",
    "name": "Macaquinho Drop Ad.",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "85.45",
    "margin": "122.24",
    "price": "189.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "257",
    "name": "Macaquinho LD Glow",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "80.95",
    "margin": "122.24",
    "price": "179.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "262",
    "name": "Macaquinho C/Bolso PL",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "116.95",
    "margin": "122.23",
    "price": "259.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "267",
    "name": "Macaquinho Liso Básico",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "70.88",
    "margin": "122.21",
    "price": "157.50",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "268",
    "name": "Macaquinho Frente Única",
    "category": "Macaquinho",
    "size": "Único",
    "cost": "94.45",
    "margin": "122.23",
    "price": "209.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "185",
    "name": "Body Onça",
    "category": "Maiô",
    "size": "Único",
    "cost": "53.96",
    "margin": "122.20",
    "price": "119.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "171",
    "name": "Regata Dry Fit - Alpha",
    "category": "Regata",
    "size": "Único",
    "cost": "26.95",
    "margin": "122.26",
    "price": "59.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "173",
    "name": "Regata Apex - Alpha",
    "category": "Regata",
    "size": "Único",
    "cost": "44.96",
    "margin": "122.20",
    "price": "99.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "174",
    "name": "Regata Oversized - Alpha",
    "category": "Regata",
    "size": "Único",
    "cost": "44.96",
    "margin": "122.20",
    "price": "99.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "180",
    "name": "Regata Tule",
    "category": "Regata",
    "size": "Único",
    "cost": "33.71",
    "margin": "122.19",
    "price": "74.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "184",
    "name": "Regata Dry Fit - Fem. Aberta",
    "category": "Regata",
    "size": "Único",
    "cost": "33.75",
    "margin": "122.22",
    "price": "75.00",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "186",
    "name": "Regata Avulso",
    "category": "Regata",
    "size": "Único",
    "cost": "31.46",
    "margin": "122.19",
    "price": "69.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "182",
    "name": "Short - Alpha",
    "category": "Short",
    "size": "Único",
    "cost": "34.16",
    "margin": "122.19",
    "price": "75.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "189",
    "name": "Short Duo",
    "category": "Short",
    "size": "Único",
    "cost": "44.96",
    "margin": "122.20",
    "price": "99.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "190",
    "name": "Short Neon",
    "category": "Short",
    "size": "Único",
    "cost": "24.75",
    "margin": "122.22",
    "price": "55.00",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "191",
    "name": "Short Empina",
    "category": "Short",
    "size": "Único",
    "cost": "49.46",
    "margin": "122.20",
    "price": "109.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "192",
    "name": "Short Brilhante",
    "category": "Short",
    "size": "Único",
    "cost": "35.96",
    "margin": "122.19",
    "price": "79.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "1",
    "name": "TAXA DE ENTREGA",
    "category": "Taxa De Entrega",
    "size": "Único",
    "cost": "0.00",
    "margin": "0.00",
    "price": "0.00",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "181",
    "name": "Top - Alpha",
    "category": "Top",
    "size": "Único",
    "cost": "40.46",
    "margin": "122.19",
    "price": "89.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "187",
    "name": "Cropped Manga Curta",
    "category": "Top",
    "size": "Único",
    "cost": "31.46",
    "margin": "122.19",
    "price": "69.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "188",
    "name": "Top (Cropped) Manga Longa",
    "category": "Top",
    "size": "Único",
    "cost": "40.46",
    "margin": "122.19",
    "price": "89.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "193",
    "name": "Top Plus",
    "category": "Top",
    "size": "Único",
    "cost": "32.81",
    "margin": "122.19",
    "price": "72.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "196",
    "name": "Tops Diversos",
    "category": "Top",
    "size": "Único",
    "cost": "31.46",
    "margin": "122.19",
    "price": "69.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "197",
    "name": "Top (Cropped)",
    "category": "Top",
    "size": "Único",
    "cost": "40.46",
    "margin": "122.19",
    "price": "89.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "198",
    "name": "Top Faixa (Duo)",
    "category": "Top",
    "size": "Único",
    "cost": "35.91",
    "margin": "122.22",
    "price": "79.80",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "199",
    "name": "Top Duo",
    "category": "Top",
    "size": "Único",
    "cost": "44.96",
    "margin": "122.20",
    "price": "99.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "297",
    "name": "Top frente unica",
    "category": "Top",
    "size": "Único",
    "cost": "35.96",
    "margin": "122.19",
    "price": "79.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  },
  {
    "code": "300",
    "name": "Top Nadador",
    "category": "Top",
    "size": "Único",
    "cost": "35.96",
    "margin": "122.19",
    "price": "79.90",
    "stock": 0,
    "minStock": 0,
    "ncm": null
  }
] as const;
